name: Mark Tharme
favicon: null
layout_spectrum: 0.44114474137313664
typography_spectrum: 0.9606679345015436
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.31509541254490614
  lightness: 0.9804183763917536
  saturation: 0.07803123514167964
  rhythmicContrast: 0.8997323515359312
purpose: []
